=== JVerbeek/TCPDBench/datasets/schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://example.com/root.json",
	"type": "object",
	"title": "Result Schema",
	"default": null,
	"required": [
		"script",
		"hostname",
		"dataset",
		"command",
		"status",
		"error",
		"parameters",
		"result"
	],
	"properties": {
		"script": {
			"$id": "#/properties/script",
			"type": "string",
			"title": "The Script Schema",
			"description": "Absolute path to the script that created the result.",
			"pattern": "^(.*)$"
		},
		"script_md5": {
			"$id": "#/properties/script_md5",
			"type": "string",
			"title": "The Script_md5 Schema",
			"description": "MD5 checksum of the script file",
			"pattern": "^[a-z0-9]{32}$"
		},
		"hostname": {
			"$id": "#/properties/hostname",
			"type": "string",
			"title": "The Hostname Schema",
			"description": "Hostname of the machine that ran the task",
			"pattern": "^(.*)$"
		},
		"dataset": {
			"$id": "#/properties/dataset",
			"type": "string",
			"title": "The Dataset Schema",
			"description": "Name of the dataset",
			"pattern": "^[a-z_0-9]+$"
		},
		"dataset_md5": {
			"$id": "#/properties/dataset_md5",
			"type": "string",
			"title": "The Dataset_md5 Schema",
			"description": "MD5 checksum of the dataset file",
			"pattern": "^[a-z0-9]{32}$"
		},
		"command": {
			"$id": "#/properties/command",
			"type": "string",
			"title": "The Command Schema",
			"description": "The exact command that was executed",
			"pattern": "^(.*)$"
		},
		"status": {
			"$id": "#/properties/status",
			"type": "string",
			"enum": [
				"FAIL",
				"SKIP",
				"SUCCESS",
				"TIMEOUT"
			],
			"title": "The Status Schema",
			"description": "Return status of the task"
		},
		"error": {
			"$id": "#/properties/error",
			"type": ["string", "null"],
			"title": "The Error Schema",
			"description": "An error message, if one occurred",
			"default": null,
			"pattern": "^(.*)$"
		},
		"parameters": {
			"$id": "#/properties/parameters",
			"type": "object",
			"title": "The Parameters Schema",
			"description": "Parameters to the algorithm",
			"default": null
		},
		"result": {
			"$id": "#/properties/result",
			"type": "object",
			"title": "The Result Schema",
			"required": [
				"cplocations",
				"runtime"
			],
			"properties": {
				"cplocations": {
					"$id": "#/properties/result/properties/cplocations",
					"type": ["array", "null"],
					"title": "The Cplocations Schema",
					"description": "Array of change point locations as 0-based integers",
					"default": null
				},
				"runtime": {
					"$id": "#/properties/result/properties/runtime",
					"type": ["number", "null"],
					"title": "The Runtime Schema",
					"description": "The runtime of the task, in seconds.",
					"default": null
				}
			}
		}
	}
}

=== JVerbeek/TCPDBench/stagedir/0/df629ace3e15a441.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/gdp_argentina.json -p BIC -f mean -t Normal -m SegNeigh -Q default",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R",
	"script_md5" : "6175ed267f515e2958637075675272db",
	"hostname" : "hex-portable",
	"dataset" : "gdp_argentina",
	"dataset_md5" : "694212b5682ebd808d740ffd83d4bc16",
	"status" : "SUCCESS",
	"parameters" : {
		"Q" : 5,
		"func" : "mean",
		"max_cp" : "default",
		"method" : "SegNeigh",
		"penalty" : "BIC",
		"test_statistic" : "Normal"
	},
	"result" : {
		"cplocations" : [
			31,
			46,
			58
		],
		"runtime" : 0.003128052
	}
}

=== JVerbeek/TCPDBench/tmp/e2b1f60b1d158a19.json
{
	"error" : "This method has no support for multidimensional data.",
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_prophet.R --args -i /home/janneke/TCPDBench/datasets/run_log.json -N default",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_prophet.R",
	"script_md5" : "651dab1a04514f68e3d9719059dbc93f",
	"hostname" : "hex-portable",
	"dataset" : "run_log",
	"dataset_md5" : "2c78a8fa0b4a2f8e2d22ba3ad4dfd49f",
	"status" : "SKIP",
	"parameters" : {
		"changepoint.range" : 1,
		"threshold" : 0.01,
		"yearly.seasonality" : "auto",
		"weekly.seasonality" : "auto",
		"daily.seasonality" : "auto",
		"Nmax" : 25
	},
	"result" : {
		"cplocations" : null,
		"runtime" : null
	}
}

=== JVerbeek/TCPDBench/abed_results/quality_control_4/default_bocpd/bcd3ea7924abee64.json
{"error": "None", "command": "/usr/lib/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_ocp.R --args -i /home/janneke/TCPDBench/datasets/quality_control_4.json -l 100 --prior-a 1.0 --prior-b 1.0 --prior-k 1.0", "script": "/home/janneke/TCPDBench/execs/R/cpdbench_ocp.R", "script_md5": "909dde17ff91cf60fd649fd6e75ac2fd", "hostname": "hex", "dataset": "quality_control_4", "dataset_md5": "1efedb9a52cd0b9a9250cf9781c5f7ef", "status": "SUCCESS", "parameters": {"missPts": "none", "cpthreshold": 0.5, "truncRlim": 0.0001, "minRlength": 1, "maxRlength": 10000, "minsep": 1, "maxsep": 10000, "multivariate": false, "lambda": 100, "prior_a": 1, "prior_b": 1, "prior_k": 1}, "result": {"cplocations": [0, 158, 197, 267, 289, 342, 468, 488], "runtime": 0.2278986}}

=== JVerbeek/TCPDBench/stagedir/0/cfe1aabd6562485e.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/measles.json -p MBIC -f mean -t Normal -m PELT",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R",
	"script_md5" : "6175ed267f515e2958637075675272db",
	"hostname" : "hex-portable",
	"dataset" : "measles",
	"dataset_md5" : "e42afd03be893fc7deb98514c94fa4c7",
	"status" : "SUCCESS",
	"parameters" : {
		"func" : "mean",
		"max_cp" : "max",
		"method" : "PELT",
		"penalty" : "MBIC",
		"test_statistic" : "Normal"
	},
	"result" : {
		"cplocations" : [
			149,
			178,
			255,
			275,
			369,
			393,
			472,
			496,
			572,
			596,
			681,
			701,
			777,
			807,
			990
		],
		"runtime" : 0.001526117
	}
}

=== JVerbeek/TCPDBench/stagedir/0/f927e9906db73375.json
{
	"error" : "This method has no support for multidimensional data.",
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/occupancy.json -p BIC -f mean -t Normal -m SegNeigh -Q default",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R",
	"script_md5" : "6175ed267f515e2958637075675272db",
	"hostname" : "hex-portable",
	"dataset" : "occupancy",
	"dataset_md5" : "bc6cd9adaf496fe30bf0e417d2c3b0c6",
	"status" : "SKIP",
	"parameters" : {
		"Q" : 5,
		"func" : "mean",
		"max_cp" : "default",
		"method" : "SegNeigh",
		"penalty" : "BIC",
		"test_statistic" : "Normal"
	},
	"result" : {
		"cplocations" : null,
		"runtime" : null
	}
}

=== JVerbeek/TCPDBench/abed_results/quality_control_2/default_amoc/6eceecd535366e0c.json
{"error": "None", "command": "/usr/lib/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/quality_control_2.json -p MBIC -f mean -t Normal -m AMOC", "script": "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R", "script_md5": "6175ed267f515e2958637075675272db", "hostname": "hex", "dataset": "quality_control_2", "dataset_md5": "919a55440bd00d635db80fe83e921c7d", "status": "SUCCESS", "parameters": {"func": "mean", "max_cp": "max", "method": "AMOC", "penalty": "MBIC", "test_statistic": "Normal"}, "result": {"cplocations": [96], "runtime": 0.002183199}}

=== JVerbeek/TCPDBench/stagedir/0/ea828f596f87775b.json
{
	"error" : "Missing value: NA is not allowed in the data as changepoint methods are only sensible for regularly spaced data.",
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/uk_coal_employ.json -p MBIC -f mean -t Normal -m AMOC",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R",
	"script_md5" : "6175ed267f515e2958637075675272db",
	"hostname" : "hex-portable",
	"dataset" : "uk_coal_employ",
	"dataset_md5" : "a7c72746e46d6e09f516bd87e0e68bef",
	"status" : "FAIL",
	"parameters" : {
		"func" : "mean",
		"max_cp" : "max",
		"method" : "AMOC",
		"penalty" : "MBIC",
		"test_statistic" : "Normal"
	},
	"result" : {
		"cplocations" : null,
		"runtime" : null
	}
}

=== JVerbeek/TCPDBench/stagedir/0/c5bdb09bfb209a0d.json
{
	"command": "/home/janneke/TCPDBench/execs/python/cpdbench_zero.py -i /home/janneke/TCPDBench/datasets/ozone.json",
	"dataset": "ozone",
	"dataset_md5": "348b1f85c3ec3da3b8989afe04c33b80",
	"error": null,
	"hostname": "hex-portable",
	"parameters": {},
	"result": {
		"cplocations": [],
		"runtime": 4.76837158203125e-07
	},
	"script": "/home/janneke/TCPDBench/execs/python/cpdbench_zero.py",
	"script_md5": "95b65ddd5669b41385966a4aad387118",
	"status": "SUCCESS"
}
