=== JVerbeek/TCPDBench/datasets/schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://example.com/root.json",
	"type": "object",
	"title": "Result Schema",
	"default": null,
	"required": [
		"script",
		"hostname",
		"dataset",
		"command",
		"status",
		"error",
		"parameters",
		"result"
	],
	"properties": {
		"script": {
			"$id": "#/properties/script",
			"type": "string",
			"title": "The Script Schema",
			"description": "Absolute path to the script that created the result.",
			"pattern": "^(.*)$"
		},
		"script_md5": {
			"$id": "#/properties/script_md5",
			"type": "string",
			"title": "The Script_md5 Schema",
			"description": "MD5 checksum of the script file",
			"pattern": "^[a-z0-9]{32}$"
		},
		"hostname": {
			"$id": "#/properties/hostname",
			"type": "string",
			"title": "The Hostname Schema",
			"description": "Hostname of the machine that ran the task",
			"pattern": "^(.*)$"
		},
		"dataset": {
			"$id": "#/properties/dataset",
			"type": "string",
			"title": "The Dataset Schema",
			"description": "Name of the dataset",
			"pattern": "^[a-z_0-9]+$"
		},
		"dataset_md5": {
			"$id": "#/properties/dataset_md5",
			"type": "string",
			"title": "The Dataset_md5 Schema",
			"description": "MD5 checksum of the dataset file",
			"pattern": "^[a-z0-9]{32}$"
		},
		"command": {
			"$id": "#/properties/command",
			"type": "string",
			"title": "The Command Schema",
			"description": "The exact command that was executed",
			"pattern": "^(.*)$"
		},
		"status": {
			"$id": "#/properties/status",
			"type": "string",
			"enum": [
				"FAIL",
				"SKIP",
				"SUCCESS",
				"TIMEOUT"
			],
			"title": "The Status Schema",
			"description": "Return status of the task"
		},
		"error": {
			"$id": "#/properties/error",
			"type": ["string", "null"],
			"title": "The Error Schema",
			"description": "An error message, if one occurred",
			"default": null,
			"pattern": "^(.*)$"
		},
		"parameters": {
			"$id": "#/properties/parameters",
			"type": "object",
			"title": "The Parameters Schema",
			"description": "Parameters to the algorithm",
			"default": null
		},
		"result": {
			"$id": "#/properties/result",
			"type": "object",
			"title": "The Result Schema",
			"required": [
				"cplocations",
				"runtime"
			],
			"properties": {
				"cplocations": {
					"$id": "#/properties/result/properties/cplocations",
					"type": ["array", "null"],
					"title": "The Cplocations Schema",
					"description": "Array of change point locations as 0-based integers",
					"default": null
				},
				"runtime": {
					"$id": "#/properties/result/properties/runtime",
					"type": ["number", "null"],
					"title": "The Runtime Schema",
					"description": "The runtime of the task, in seconds.",
					"default": null
				}
			}
		}
	}
}

=== JVerbeek/TCPDBench/stagedir/0/d132e9d3933716c3.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_ocp.R --args -i /home/janneke/TCPDBench/datasets/occupancy.json -l 100 --prior-a 1.0 --prior-b 1.0 --prior-k 1.0",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_ocp.R",
	"script_md5" : "909dde17ff91cf60fd649fd6e75ac2fd",
	"hostname" : "hex-portable",
	"dataset" : "occupancy",
	"dataset_md5" : "bc6cd9adaf496fe30bf0e417d2c3b0c6",
	"status" : "SUCCESS",
	"parameters" : {
		"missPts" : "none",
		"cpthreshold" : 0.5,
		"truncRlim" : 0.0001,
		"minRlength" : 1,
		"maxRlength" : 10000,
		"minsep" : 1,
		"maxsep" : 10000,
		"multivariate" : true,
		"lambda" : 100,
		"prior_a" : 1,
		"prior_b" : 1,
		"prior_k" : 1
	},
	"result" : {
		"cplocations" : [
			0,
			8,
			52,
			58,
			91,
			94,
			142,
			181,
			185,
			239,
			264,
			285,
			341,
			351,
			416,
			419,
			439,
			451,
			461,
			506
		],
		"runtime" : 0.3224378
	}
}

=== JVerbeek/TCPDBench/stagedir/0/bb7cc75cc9e8834e.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_ecp.R --args -i /home/janneke/TCPDBench/datasets/gdp_argentina.json -a e.divisive --alpha 1.0 --minsize 30 --runs 199 --siglvl 0.05",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_ecp.R",
	"script_md5" : "1b71ad311b8354aa3d1594488eb7dea2",
	"hostname" : "hex-portable",
	"dataset" : "gdp_argentina",
	"dataset_md5" : "694212b5682ebd808d740ffd83d4bc16",
	"status" : "SUCCESS",
	"parameters" : {
		"k" : "null",
		"algorithm" : "e.divisive",
		"alpha" : 1,
		"cost" : 1,
		"maxcp" : null,
		"minsize" : 30,
		"runs" : 199,
		"siglvl" : 0.05
	},
	"result" : {
		"cplocations" : [
			0,
			59
		],
		"runtime" : 0.001590014
	}
}

=== JVerbeek/TCPDBench/abed_results/quality_control_4/default_binseg/7ae2f18244dcf6d9.json
{"error": "None", "command": "/usr/lib/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/quality_control_4.json -p MBIC -f mean -t Normal -m BinSeg -Q default", "script": "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R", "script_md5": "6175ed267f515e2958637075675272db", "hostname": "hex", "dataset": "quality_control_4", "dataset_md5": "1efedb9a52cd0b9a9250cf9781c5f7ef", "status": "SUCCESS", "parameters": {"Q": 5, "func": "mean", "max_cp": "default", "method": "BinSeg", "penalty": "MBIC", "test_statistic": "Normal"}, "result": {"cplocations": [157, 287, 341, 467, 499], "runtime": 0.00696969}}

=== JVerbeek/TCPDBench/tmp/fb62bbc029cf8c0e.json
{
	"error" : "This method has no support for multidimensional data.",
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/bee_waggle_6.json -p MBIC -f mean -t Normal -m PELT",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R",
	"script_md5" : "6175ed267f515e2958637075675272db",
	"hostname" : "hex-portable",
	"dataset" : "bee_waggle_6",
	"dataset_md5" : "4f03feafecb3be0b069b3cb0d6b17d4f",
	"status" : "SKIP",
	"parameters" : {
		"func" : "mean",
		"max_cp" : "max",
		"method" : "PELT",
		"penalty" : "MBIC",
		"test_statistic" : "Normal"
	},
	"result" : {
		"cplocations" : null,
		"runtime" : null
	}
}

=== JVerbeek/TCPDBench/stagedir/0/e5727f20e5808941.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_ecp.R --args -i /home/janneke/TCPDBench/datasets/quality_control_1.json -a e.divisive --alpha 1.0 --minsize 30 --runs 199 --siglvl 0.05",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_ecp.R",
	"script_md5" : "1b71ad311b8354aa3d1594488eb7dea2",
	"hostname" : "hex-portable",
	"dataset" : "quality_control_1",
	"dataset_md5" : "fcfd5b0323a0dbd499c22b32c77f6a43",
	"status" : "SUCCESS",
	"parameters" : {
		"k" : "null",
		"algorithm" : "e.divisive",
		"alpha" : 1,
		"cost" : 1,
		"maxcp" : null,
		"minsize" : 30,
		"runs" : 199,
		"siglvl" : 0.05
	},
	"result" : {
		"cplocations" : [
			0,
			87,
			144,
			206,
			313
		],
		"runtime" : 0.894192
	}
}

=== JVerbeek/TCPDBench/stagedir/0/c26ea4b27309d126.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/scanline_126007.json -p BIC -f mean -t Normal -m SegNeigh -Q default",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R",
	"script_md5" : "6175ed267f515e2958637075675272db",
	"hostname" : "hex-portable",
	"dataset" : "scanline_126007",
	"dataset_md5" : "057d5741b623308af00c42e2c8e525c3",
	"status" : "SUCCESS",
	"parameters" : {
		"Q" : 5,
		"func" : "mean",
		"max_cp" : "default",
		"method" : "SegNeigh",
		"penalty" : "BIC",
		"test_statistic" : "Normal"
	},
	"result" : {
		"cplocations" : [
			291,
			324,
			375,
			402,
			480
		],
		"runtime" : 0.05772734
	}
}

=== JVerbeek/TCPDBench/tmp/c6e424cbdba772fc.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/brent_spot.json -p MBIC -f mean -t Normal -m BinSeg -Q default",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R",
	"script_md5" : "6175ed267f515e2958637075675272db",
	"hostname" : "hex-portable",
	"dataset" : "brent_spot",
	"dataset_md5" : "79892116ef8a0aa16e2450123655b31d",
	"status" : "SUCCESS",
	"parameters" : {
		"Q" : 5,
		"func" : "mean",
		"max_cp" : "default",
		"method" : "BinSeg",
		"penalty" : "MBIC",
		"test_statistic" : "Normal"
	},
	"result" : {
		"cplocations" : [
			139,
			279,
			378,
			499
		],
		"runtime" : 0.001363993
	}
}

=== JVerbeek/TCPDBench/stagedir/0/afd25f76e06c60ba.json
{
	"error" : null,
	"command" : "/usr/lib/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_prophet.R --args -i /home/janneke/TCPDBench/datasets/construction.json -N default",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_prophet.R",
	"script_md5" : "651dab1a04514f68e3d9719059dbc93f",
	"hostname" : "hex",
	"dataset" : "construction",
	"dataset_md5" : "fb0347dc9fd353b11b35e99f7d531f13",
	"status" : "SUCCESS",
	"parameters" : {
		"changepoint.range" : 1,
		"threshold" : 0.01,
		"yearly.seasonality" : "auto",
		"weekly.seasonality" : "auto",
		"daily.seasonality" : "auto",
		"Nmax" : 25
	},
	"result" : {
		"cplocations" : [
			76,
			89,
			102,
			114,
			127,
			140,
			153,
			229
		],
		"runtime" : 0.2675447
	}
}
