=== JVerbeek/TCPDBench/datasets/schema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://example.com/root.json",
	"type": "object",
	"title": "Result Schema",
	"default": null,
	"required": [
		"script",
		"hostname",
		"dataset",
		"command",
		"status",
		"error",
		"parameters",
		"result"
	],
	"properties": {
		"script": {
			"$id": "#/properties/script",
			"type": "string",
			"title": "The Script Schema",
			"description": "Absolute path to the script that created the result.",
			"pattern": "^(.*)$"
		},
		"script_md5": {
			"$id": "#/properties/script_md5",
			"type": "string",
			"title": "The Script_md5 Schema",
			"description": "MD5 checksum of the script file",
			"pattern": "^[a-z0-9]{32}$"
		},
		"hostname": {
			"$id": "#/properties/hostname",
			"type": "string",
			"title": "The Hostname Schema",
			"description": "Hostname of the machine that ran the task",
			"pattern": "^(.*)$"
		},
		"dataset": {
			"$id": "#/properties/dataset",
			"type": "string",
			"title": "The Dataset Schema",
			"description": "Name of the dataset",
			"pattern": "^[a-z_0-9]+$"
		},
		"dataset_md5": {
			"$id": "#/properties/dataset_md5",
			"type": "string",
			"title": "The Dataset_md5 Schema",
			"description": "MD5 checksum of the dataset file",
			"pattern": "^[a-z0-9]{32}$"
		},
		"command": {
			"$id": "#/properties/command",
			"type": "string",
			"title": "The Command Schema",
			"description": "The exact command that was executed",
			"pattern": "^(.*)$"
		},
		"status": {
			"$id": "#/properties/status",
			"type": "string",
			"enum": [
				"FAIL",
				"SKIP",
				"SUCCESS",
				"TIMEOUT"
			],
			"title": "The Status Schema",
			"description": "Return status of the task"
		},
		"error": {
			"$id": "#/properties/error",
			"type": ["string", "null"],
			"title": "The Error Schema",
			"description": "An error message, if one occurred",
			"default": null,
			"pattern": "^(.*)$"
		},
		"parameters": {
			"$id": "#/properties/parameters",
			"type": "object",
			"title": "The Parameters Schema",
			"description": "Parameters to the algorithm",
			"default": null
		},
		"result": {
			"$id": "#/properties/result",
			"type": "object",
			"title": "The Result Schema",
			"required": [
				"cplocations",
				"runtime"
			],
			"properties": {
				"cplocations": {
					"$id": "#/properties/result/properties/cplocations",
					"type": ["array", "null"],
					"title": "The Cplocations Schema",
					"description": "Array of change point locations as 0-based integers",
					"default": null
				},
				"runtime": {
					"$id": "#/properties/result/properties/runtime",
					"type": ["number", "null"],
					"title": "The Runtime Schema",
					"description": "The runtime of the task, in seconds.",
					"default": null
				}
			}
		}
	}
}

=== JVerbeek/TCPDBench/stagedir/0/ced1fb44c3e41113.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_wbs.R --args -i /home/janneke/TCPDBench/datasets/usd_isk.json -K default -p SSIC -g true",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_wbs.R",
	"script_md5" : "155041b2e01ba0b7ece7753cb145ea9a",
	"hostname" : "hex-portable",
	"dataset" : "usd_isk",
	"dataset_md5" : "5cac2807a0e280c8ffd7321662e339ac",
	"status" : "SUCCESS",
	"parameters" : {
		"M" : 5000,
		"rand.intervals" : true,
		"Kmax" : 50,
		"integrated" : true,
		"penalty" : "SSIC"
	},
	"result" : {
		"cplocations" : [
			15,
			19,
			26,
			39,
			46,
			48,
			58,
			69,
			70,
			85,
			90,
			98,
			107,
			109,
			112,
			115,
			116,
			119,
			122,
			138,
			154,
			178,
			190,
			206,
			211,
			219,
			236
		],
		"runtime" : 0.03706837
	}
}

=== JVerbeek/TCPDBench/stagedir/0/bdd62c4dc418c825.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_prophet.R --args -i /home/janneke/TCPDBench/datasets/gdp_argentina.json -N default",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_prophet.R",
	"script_md5" : "651dab1a04514f68e3d9719059dbc93f",
	"hostname" : "hex-portable",
	"dataset" : "gdp_argentina",
	"dataset_md5" : "694212b5682ebd808d740ffd83d4bc16",
	"status" : "SUCCESS",
	"parameters" : {
		"changepoint.range" : 1,
		"threshold" : 0.01,
		"yearly.seasonality" : "auto",
		"weekly.seasonality" : "auto",
		"daily.seasonality" : "auto",
		"Nmax" : 25
	},
	"result" : {
		"cplocations" : [
			26,
			28,
			30,
			35,
			37,
			39,
			42,
			44
		],
		"runtime" : 0.1935856
	}
}

=== JVerbeek/TCPDBench/stagedir/0/f3fc9cf12288af29.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepointnp.R --args -i /home/janneke/TCPDBench/datasets/scanline_126007.json -p MBIC -q 10",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepointnp.R",
	"script_md5" : "900c8687ad78bde19902400624e57d8b",
	"hostname" : "hex-portable",
	"dataset" : "scanline_126007",
	"dataset_md5" : "057d5741b623308af00c42e2c8e525c3",
	"status" : "SUCCESS",
	"parameters" : {
		"method" : "PELT",
		"test.stat" : "empirical_distribution",
		"minseglen" : 1,
		"nquantiles" : 10,
		"penalty" : "MBIC"
	},
	"result" : {
		"cplocations" : [
			106,
			113,
			163,
			250,
			265,
			279,
			291,
			306,
			315,
			324,
			353,
			363,
			375,
			402,
			480
		],
		"runtime" : 0.004576206
	}
}

=== JVerbeek/TCPDBench/tmp/f73710eb6351f3dd.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/co2_canada.json -p MBIC -f mean -t Normal -m AMOC",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R",
	"script_md5" : "6175ed267f515e2958637075675272db",
	"hostname" : "hex-portable",
	"dataset" : "co2_canada",
	"dataset_md5" : "de8d2cac911d2a8e3ce5addacbaed8e0",
	"status" : "SUCCESS",
	"parameters" : {
		"func" : "mean",
		"max_cp" : "max",
		"method" : "AMOC",
		"penalty" : "MBIC",
		"test_statistic" : "Normal"
	},
	"result" : {
		"cplocations" : [
			106
		],
		"runtime" : 0.003042221
	}
}

=== JVerbeek/TCPDBench/stagedir/0/eb7ac646de3e3735.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/homeruns.json -p MBIC -f mean -t Normal -m PELT",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R",
	"script_md5" : "6175ed267f515e2958637075675272db",
	"hostname" : "hex-portable",
	"dataset" : "homeruns",
	"dataset_md5" : "987bbab63e2c72acba1c07325303720c",
	"status" : "SUCCESS",
	"parameters" : {
		"func" : "mean",
		"max_cp" : "max",
		"method" : "PELT",
		"penalty" : "MBIC",
		"test_statistic" : "Normal"
	},
	"result" : {
		"cplocations" : [
			59,
			117
		],
		"runtime" : 0.001782179
	}
}

=== JVerbeek/TCPDBench/abed_results/shanghai_license/default_zero/45dd0e79de81cef4.json
{"command": "/home/janneke/TCPDBench/execs/python/cpdbench_zero.py -i /home/janneke/TCPDBench/datasets/shanghai_license.json", "dataset": "shanghai_license", "dataset_md5": "b4ac173eb6c0a1a4d10268abc109eda1", "error": "None", "hostname": "hex", "parameters": {}, "result": {"cplocations": [], "runtime": 4.76837158203125e-07}, "script": "/home/janneke/TCPDBench/execs/python/cpdbench_zero.py", "script_md5": "95b65ddd5669b41385966a4aad387118", "status": "SUCCESS"}

=== JVerbeek/TCPDBench/stagedir/0/f10b2007112e7d06.json
{
	"error" : null,
	"command" : "/usr/lib64/R/bin/exec/R --no-echo --no-restore --no-save --slave --file=/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R --args -i /home/janneke/TCPDBench/datasets/debt_ireland.json -p MBIC -f mean -t Normal -m BinSeg -Q default",
	"script" : "/home/janneke/TCPDBench/execs/R/cpdbench_changepoint.R",
	"script_md5" : "6175ed267f515e2958637075675272db",
	"hostname" : "hex-portable",
	"dataset" : "debt_ireland",
	"dataset_md5" : "a5a9e752c338d2ffcceb614bb2064cc9",
	"status" : "SUCCESS",
	"parameters" : {
		"Q" : 5,
		"func" : "mean",
		"max_cp" : "default",
		"method" : "BinSeg",
		"penalty" : "MBIC",
		"test_statistic" : "Normal"
	},
	"result" : {
		"cplocations" : [
			8,
			20
		],
		"runtime" : 0.001036644
	}
}

=== JVerbeek/TCPDBench/abed_results/quality_control_3/default_zero/446fc7d3f9ce48dd.json
{"command": "/home/janneke/TCPDBench/execs/python/cpdbench_zero.py -i /home/janneke/TCPDBench/datasets/quality_control_3.json", "dataset": "quality_control_3", "dataset_md5": "94f55ddedd03197bc3e660f6e1d840ee", "error": "None", "hostname": "hex", "parameters": {}, "result": {"cplocations": [], "runtime": 7.152557373046875e-07}, "script": "/home/janneke/TCPDBench/execs/python/cpdbench_zero.py", "script_md5": "95b65ddd5669b41385966a4aad387118", "status": "SUCCESS"}
